Develop
hl7ch/ch-lab-report pull request #56
Opened 2024-02-18 15:19 UTC by lpg-tech

ChLabOrganization constrains the Organization resource for the ordering and reporting bodies. Parent is CHCoreOrganization.

2024-02-20 09:56 UTC, ziegm commented on input/fsh/profiles/Organization.fsh
>  Title: "CH Organization: ordering or reporting Lab-Tests"
Title change to "CH LAB Organization: ...."?

2024-02-20 10:08 UTC, ziegm commented
@lpg-tech (fyi: @pjolo @oliveregger )
Please do not use the CH LAB Organization everywhere. You can look like EU LAB has it done:
Bundle.entry -> CH Core Organization (already definided by using CH Core Document as parent profile)
Composition.author -> CH Core Organization (dito)
Observation.performer -> CH LAB Organization 
Otherwise we have conflicts with the requirements coming from IPS (tested with CH ELM (broker scenario))

2024-02-20 10:09 UTC, ziegm requested changes
see comments

2024-02-20 11:30 UTC, lpg-tech commented
Added commit:
https://github.com/hl7ch/ch-lab-report/commit/59b5d7127728adbc5509e3959c3af5eaabf06dd7

2024-02-21 08:31 UTC, ziegm approved these changes
okay for us, thank you

2024-02-22 22:39 UTC, merged